export const funnyNames = [
    "Captain Monopoly",
    "Bankrupt Bob",
    "Richie Rich",
    "Dice Master",
    "Property Pro",
    "Rent Collector",
    "Cash King",
    "Board Boss",
    "Lucky Roller",
    "Mr. Moneybags",
    "The Landlord",
    "Mortgage Mogul",
    "Free Parking Fanatic",
    "Chance Chaser",
    "Auction Ace",
  ];